#!/usr/bin/env bash

# This is just a wrapper script so we don't have to keep re-uploading the zipped autograder.
# The script that actually does the grading is called actual_autograder

set -ex
cd /autograder/unified_ag_source
git pull
./actual_autograder

