#!/usr/bin/env bash

set -ex

cd /autograder

LEANFILES=$(find submission/ -mindepth 1 -maxdepth 1 -type f -name "*.lean" -printf x | wc -c)
TEXFILES=$(find submission/ -mindepth 1 -maxdepth 1 -type f -name "*.tex" -printf x | wc -c)
TEX_TEMPLATE=$1

# We're expecting students to submit two files, a .tex file and a .lean file, but the two autograders
# expect the submission dir to contain either one or the other. So we split them out to start.

if [ $LEANFILES == 1 ]; then 

  mkdir lean_submission
  cp submission/*.lean lean_submission/

fi
  
if [ $TEXFILES -ge 1 ]; then 

  mkdir tex_submission
  cp submission/* tex_submission/

fi


rm -rf submission

mv source unified_ag_src


#########################################
##  LEAN AUTOGRADER EXECUTION
#########################################

if [ $LEANFILES == 1 ]; then 


    mv lean_submission submission
    mv lean_ag_src source
    cd source

    git pull

    # The following line is needed for this reason:
    # we have just pulled a new version of the course project,
    # which has the autograder as a dependency.
    # If we update the version of the autograder in that project,
    # `run_autograder_main` may change.
    # So we need to make sure that the latest versions of the dependencies are present
    # before we copy that file over.

    ~/.elan/bin/lake update

    ./lake-packages/autograder/run_autograder_main

    cd ..


    # results.json should now contain lean results, now need to append tex results

    mv results/results.json lean_results.json


    mv submission lean_submission


    mv source lean_ag_src

fi


mv unified_ag_src source

#########################################
##  TEX AUTOGRADER EXECUTION
#########################################



if [ $TEXFILES -ge 1 ]; then 

    curl $TEX_TEMPLATE --output template.zip 

    unzip template.zip -d tex_template

    mv tex_template/*/*.cls tex_submission || true 
    mv tex_template/*/*.sty tex_submission || true 

    mv tex_template/*.cls tex_submission || true 
    mv tex_template/*.sty tex_submission || true 

    mv tex_submission submission

    cd submission

    # The OR is so that a compilation failure doesn't ruin the whole autograding script.
    ../source/scripts/grade_tex || true

    cd ..

    mv results/results.json tex_results.json

fi

python3 source/scripts/combine_json.py
